# Generated by Django 5.1.2 on 2024-10-28 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('porteiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('numero_casa', models.PositiveSmallIntegerField(verbose_name='Número da Casa a ser visitada')),
                ('placa_veiculo', models.CharField(blank=True, max_length=7, null=True, verbose_name='Placa do Veículo')),
                ('horario_chegada', models.DateTimeField(auto_now=True, verbose_name='Horário de Chegada')),
                ('horario_saida', models.DateTimeField(blank=True, null=True, verbose_name='Horário de Saída')),
                ('horario_autorizacao', models.DateTimeField(blank=True, null=True, verbose_name='Horário de Autorização de entrada')),
                ('morador_responsavel', models.CharField(blank=True, max_length=255, verbose_name='Morador Responsável por Autorizar a Entrada do Visitante')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='porteiros.porteiros', verbose_name='Porteiro que registrou a entrada do visitante')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'db_table': 'visitantes',
            },
        ),
    ]
